### ISSUE TITLE
How to handle dispatch_http_call/other timeout

### ISSUE THREAD

**Issue by danielphan2003** [Kong/ngx_wasm_module#622]
Even though you can specify timeout in dispatch_http_call Rust SDK, it doesn't seem to return any Status and the function stops instead. Same case for invalid upstream.

**Comment by casimiro** [comment]
I'm not properly familiarized with Envoy's codebase, but it seems to me that the headers of the response are defined before `Context::onHttpCallFailure` is called. 

I did some investigation on `AsyncClientImpl`, and some other classes in the `Envoy::Http` namespace, but could not pinpoint exactly where/when `:status` header is ever written.

Time is quite scarce this week so I couldn't invest much in this issue.

**Comment by hishamhm** [comment]
Ah, I did look at this yesterday but I ended up not sending the message.

> how Envoy gets from [status = BrokenConnection](https://github.com/envoyproxy/envoy/blob/0b90f64539c88dc3d2a6792dc714e8207bce0c08/source/extensions/common/wasm/context.cc#L1816) to returning a 504 status code on get_http_call_response_header(":status") 

From what I could gather, I don't think it does. From looking at the code, the BrokenConnection status (which translates to 11 in its enum), gets saved to the context `status_code_` and that (along with `status_message_`) is what is returned when the client calls `proxy_get_status`. (See [proxy-wasm-cpp-host proxy_get_status](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/3212034ee6e75d54cbf91b65cc659772166442f4/include/proxy-wasm/wasm_api_impl.h#L52) [proxy-wasm-cpp-sdk getStatus](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/a982ad089d1962f1b92f4343c910c0be6b6e6280/proxy_wasm_api.h#L892). So, I haven't tested it, but my guess is that on a callout failure, calling `proxy_get_status` would return `11`, `"reset"`.

> I'm not properly familiarized with Envoy's codebase, but it seems to me that the headers of the response are defined before Context::onHttpCallFailure is called.

I got the same impression as @casimiro. The `:status` header itself comes from the response object. The [router filter onTimeout sets kDeadlineExceeded](https://github.com/envoyproxy/envoy/blob/694fd2d9ac067792cf76d18be9e1dae0de89e382/source/extensions/filters/network/generic_proxy/router/router.cc#L392), which then [translates to 504](https://github.com/envoyproxy/envoy/blob/694fd2d9ac067792cf76d18be9e1dae0de89e382/source/extensions/filters/network/generic_proxy/codecs/http1/config.cc#L179). The timeout goes into `AsyncStreamImpl::sendLocalReply`, and since `Context::onHttpCallSuccess` seems to be the only path where `http_call_response_` is set, which is where the response map that produces `:status` for the callout comes from, I believe a 504 timeout actually goes through `onHttpCallSuccess`, rather than `onHttpCallFailure`. The latter would handle things such as a failure to connect.

**Comment by thibaultcha** [comment]
@hishamhm @casimiro Thanks! 

> @thibaultcha to clarify, did you get `on_http_call_response(token_id, 0, 0, 0)` callback _and_ `get_http_call_response_header(":status")` == `"504"` within that same callback?

On running the case again this morning, it turns out this isn't the case, I'm not sure how I ended up in the `0,0,0` code path... So with the hostcalls filter on dispatch timeout we get:

```
[2024-11-13 08:11:48.357][27958][info][wasm] [source/extensions/common/wasm/context.cc:1195] wasm log my_wasm_filter: [hostcalls] testing in "RequestHeaders"
[2024-11-13 08:11:50.359][27958][info][wasm] [source/extensions/common/wasm/context.cc:1195] wasm log my_wasm_filter: [hostcalls] on_http_call_response (id: 4, status: 504, headers: 3, body_bytes: 24, trailers: 0, op: )
```

So the timeout (after 2s) does indeed enter the `Context::onHttpCallSuccess` path. That said it seems Envoy does things I wouldn't expect and we'll have to adapt in our codebase: it produces a default response that it gives to `on_http_call_response`: the `504` + `3 headers` + a plain text body that says `upstream request timeout` (`24` bytes).

This helps a lot, thanks.

That said there remains a few unknowns for me:

- What must happen for the `Context::onHttpCallFailure` to be called and invoke the `on_http_call_response(token_id, 0, 0, 0)` callback?
- What other kind of response status/body does the "bad upstream" case produces (as it invokes `Context::onHttpCallSuccess`)?

**Comment by hishamhm** [comment]
> What must happen for the Context::onHttpCallFailure to be called and invoke the on_http_call_response(token_id, 0, 0, 0) callback?

I assume it's something like a failure to connect (e.g. trying to reach an upstream that doesn't resolve).

> What other kind of response status/body does the "bad upstream" case produces (as it invokes Context::onHttpCallSuccess)?

There are other code paths there which trigger `completeAndSendLocalReply` with `kUnavailable`, which translates to 503. They seem to be Envoy-specific as they carry status messages such as `"cluster_maintain_mode"` and `"no_healthy_upstream"`.

**Comment by thibaultcha** [comment]
@danielphan2003 We now have #625 merged which will allow filter authors to catch such failures. It should make it in the 3.9 Kong release (probably 3.9.1 which is I think 5-6 weeks from now). Or if you use the module standalone, then it's already available. We also have a guide on HTTP dispatch calls with the module: https://github.com/Kong/ngx_wasm_module/blob/main/docs/PROXY_WASM.md#http-dispatches
